/**
 * ============================================================================
 *  SiteTrack — Construction Site Live Attendance & Workforce Management System
 *  Backend for Google Apps Script (Web App) + Google Sheets (database)
 * ============================================================================
 *  FILE: 00_Config.gs
 *  ROLE: Constants, database schema (tab names + header rows + dropdowns),
 *        Script-Property key names, role & permission catalogue.
 *
 *  Nothing in this file performs I/O. It is pure configuration so that the
 *  schema is defined exactly once and every other module reads it from here.
 * ============================================================================
 */

/** Product / version metadata returned by the `ping` action. */
var SITETRACK_APP = {
  name: 'SiteTrack',
  version: '1.0.0',
  schemaVersion: 1,
  build: 'gas-sheets-v1'
};

/**
 * Script Properties keys. Secrets live ONLY here — never hard-coded in code.
 * Set them with the `setScriptProperty` action (owner only) or in
 * Apps Script → Project Settings → Script Properties.
 */
var PROP = {
  MASTER_ID: 'PLATFORM_MASTER_ID',   // Spreadsheet ID of the Platform Master Sheet
  OWNER_KEY: 'OWNER_KEY',            // Secret key used by the Platform Owner panel
  OWNER_EMAIL: 'OWNER_EMAIL',        // Platform owner notification e-mail
  TOKEN_SECRET: 'TOKEN_SECRET',      // HMAC secret for session tokens
  DRIVE_ROOT_ID: 'DRIVE_ROOT_ID',    // Root Drive folder holding per-company folders
  TIMEZONE: 'TIMEZONE',              // Platform default timezone
  DEV_MODE: 'DEV_MODE',              // 'true' echoes OTP codes in API responses - dev only, never production
  WHATSAPP_TOKEN: 'WHATSAPP_TOKEN',  // optional WhatsApp Cloud API
  WHATSAPP_PHONE_ID: 'WHATSAPP_PHONE_ID',
  MAPS_API_KEY: 'MAPS_API_KEY',      // optional Google Geocoding API key
  WEATHER_ENABLED: 'WEATHER_ENABLED',
  ALLOW_UNVERIFIED_SIGNUP: 'ALLOW_UNVERIFIED_SIGNUP',
  SELFIE_MAX_BYTES: 'SELFIE_MAX_BYTES',
  MAIL_FROM_NAME: 'MAIL_FROM_NAME'
};

/** Roles. `PlatformOwner` is virtual — it never lives in a company Users tab. */
var ROLES = {
  OWNER: 'PlatformOwner',
  SUPER_ADMIN: 'SuperAdmin',
  ADMIN: 'Admin',
  SUB_ADMIN: 'SubAdmin',
  EMPLOYEE: 'Employee'
};

var ROLE_LIST = ['SuperAdmin', 'Admin', 'SubAdmin', 'Employee'];

/**
 * Granular permission toggles used by the Sub-Admin builder (§2.1).
 * Every write action is checked against these server-side (§12.7).
 */
var PERMISSIONS = [
  'createProjects', 'editProjects', 'deleteProjects',
  'createEmployees', 'editEmployees', 'deactivateEmployees',
  'manageAdmins',
  'approveLeave', 'approveExpense', 'approveTransfer',
  'reviewAttendance', 'approveRegularization',
  'viewReports', 'exportReports',
  'manageVendors',
  'manageGeofence', 'manageSettings', 'manageHolidays', 'manageShifts',
  'manageDocuments', 'viewAuditLog', 'viewAllEmployees', 'runPayroll'
];

/** Default permission grants per role. */
var ROLE_DEFAULT_PERMISSIONS = {
  SuperAdmin: 'ALL',
  Admin: [
    'createProjects', 'editProjects',
    'createEmployees', 'editEmployees',
    'approveLeave', 'approveExpense', 'approveTransfer',
    'reviewAttendance', 'approveRegularization',
    'viewReports', 'exportReports',
    'manageVendors', 'manageDocuments',
    'viewAllEmployees', 'runPayroll'
  ],
  SubAdmin: [],
  Employee: []
};

/** Attendance states (§5). */
var ATT_STATUS = [
  'Present', 'Absent', 'HalfDay', 'Leave', 'Travel', 'Transfer',
  'Holiday', 'WeekOff', 'Flagged', 'Late'
];

var ATT_SOURCE = ['GPS', 'QR', 'Manual', 'Offline', 'System'];

var LEAVE_TYPES = ['Paid', 'Unpaid', 'Sick', 'Casual', 'HalfDay', 'WeekOff'];

var EXPENSE_CATEGORIES = [
  'Travel', 'Food', 'Labour', 'Material', 'Fuel', 'Loading',
  'Tools', 'Medical', 'Misc'
];

var DOC_TYPES = [
  'AadhaarCard', 'PANCard', 'VoterID', 'DrivingLicense', 'BankPassbook',
  'SafetyCertificate', 'MedicalFitness', 'SkillCertificate',
  'InsurancePolicy', 'WorkPermit', 'Photo', 'Resume', 'Other'
];

var INDUSTRY_TYPES = [
  'Interior Fit-out', 'Scaffolding', 'General Construction',
  'MEP / Electrical', 'Civil Infrastructure', 'Other'
];

/** Company settings written on onboarding (§3 step 5). */
var DEFAULT_SETTINGS = {
  companyName: '',
  companyLogoLink: '',
  defaultGeofenceRadius: '200',
  attendanceWindowStart: '06:00',
  attendanceWindowEnd: '11:00',
  cutoffTime: '11:00',
  outWindowStart: '16:00',
  outWindowEnd: '23:59',
  timezone: 'Asia/Kolkata',
  workingDays: '1,2,3,4,5,6',       // 0=Sunday … 6=Saturday
  weeklyOff: '0',
  lateGraceMinutes: '15',
  halfDayHours: '4',
  standardHours: '8',
  overtimeAfterHours: '9',
  overtimeRate: '1.5',
  reportFooterText: 'Generated by SiteTrack — GPS verified attendance record.',
  reportIncludeLogo: 'Y',
  reportIncludeClientPmc: 'Y',
  gpsRetentionMonths: '12',
  requireSelfie: 'Y',
  requireDeviceBinding: 'Y',
  allowQrFallback: 'Y',
  qrFallbackRadius: '1000',
  autoRainDayFlag: 'N',
  rainThresholdMm: '20',
  notifyOnFlagged: 'Y',
  notifyChannel: 'Email',
  maxGpsAccuracy: '500',            // marks with a worse fix than this are flagged
  offlineMaxAgeHours: '26',         // how long an offline-captured mark stays valid
  breakMinutes: '0',
  paidHolidays: 'Y',
  payrollDaysBasis: '26',           // monthly salary ÷ this = per-day rate
  expenseProofRequired: 'N',
  autoMonthlyReport: 'Y',
  reportRecipients: '',             // extra comma-separated e-mails for the 1st-of-month report
  heatThresholdC: '45',
  projectCodePrefix: '',
  currency: 'INR',
  setupCompleted: 'N',
  companyAddress: '',
  gst: '',
  industryType: ''
};

/**
 * ============================================================================
 *  DATABASE SCHEMA (§6 / §11)
 *  For every tab: the exact header row (spec columns first, then the extra
 *  operational columns the engine needs), dropdown validations and the
 *  columns that receive conditional formatting.
 * ============================================================================
 */
var PLATFORM_TABS = {
  CompanySignupRequests: {
    headers: [
      'RequestID', 'CompanyName', 'GST', 'Address', 'ContactPerson', 'Email',
      'Mobile', 'IndustryType', 'Status', 'SubmittedAt', 'ReviewedBy', 'ReviewNote',
      'Designation', 'LogoLink', 'CompanyID', 'OtpVerified', 'ReviewedAt'
    ],
    dropdowns: {
      Status: ['Pending', 'Approved', 'Rejected'],
      IndustryType: INDUSTRY_TYPES,
      OtpVerified: ['Y', 'N']
    },
    statusColumns: ['Status']
  },
  CompanyRegistry: {
    headers: [
      'CompanyID', 'CompanyName', 'SheetID', 'SuperAdminEmail', 'Status',
      'CreatedAt', 'PlanTier',
      'GST', 'Mobile', 'ContactPerson', 'IndustryType', 'DriveFolderID',
      'SuperAdminUserID', 'TimeZone', 'SuspendedReason', 'LastActiveAt', 'EmployeeCount'
    ],
    dropdowns: {
      Status: ['Active', 'Suspended', 'Pending', 'Closed'],
      PlanTier: ['Free', 'Pro', 'Enterprise']
    },
    statusColumns: ['Status']
  },
  /**
   * Global login directory. One row per lookup key (mobile / e-mail / user id)
   * so a single sign-in endpoint can resolve the right tenant without opening
   * every company spreadsheet.
   */
  LoginIndex: {
    headers: [
      'LookupKey', 'KeyType', 'UserID', 'CompanyID', 'Role', 'Status', 'UpdatedAt'
    ],
    dropdowns: {
      KeyType: ['Mobile', 'Email', 'UserID'],
      Status: ['Active', 'Inactive', 'Suspended']
    },
    statusColumns: ['Status']
  },
  PlatformAuditLog: {
    headers: ['LogID', 'ActorUserID', 'Action', 'TargetEntity', 'Timestamp', 'Details', 'Result'],
    dropdowns: {},
    statusColumns: []
  }
};

var COMPANY_TABS = {
  Users: {
    headers: [
      'UserID', 'Role', 'Name', 'MobileNumber', 'Email', 'PasswordHash',
      'PermissionsJSON', 'ProjectScopeJSON', 'Status', 'DeviceID', 'CreatedAt',
      'Designation', 'SalaryType', 'DailyWage', 'MonthlySalary', 'ShiftID',
      'WeeklyOff', 'Address', 'EmergencyContact', 'IdProofMasked', 'JoinedAt',
      'LastLoginAt', 'PhotoLink', 'OtpHash', 'OtpExpiry', 'MustChangePassword',
      'DeviceStatus', 'ReportsTo', 'BankAccount', 'IfscCode', 'Notes'
    ],
    dropdowns: {
      Role: ROLE_LIST,
      Status: ['Active', 'Inactive', 'Suspended'],
      SalaryType: ['Daily', 'Monthly', 'Contract'],
      DeviceStatus: ['Unbound', 'Bound', 'ChangePending', 'Blocked'],
      MustChangePassword: ['Y', 'N']
    },
    statusColumns: ['Status']
  },
  Projects: {
    headers: [
      'ProjectID', 'ProjectCode', 'Name', 'Lat', 'Long', 'GeofenceRadius',
      'WindowStart', 'WindowEnd', 'ClientName', 'ClientContact', 'PMCName',
      'PMCContact', 'StartDate', 'EndDate', 'Status',
      'Address', 'OutWindowStart', 'OutWindowEnd', 'ShiftID', 'OvertimeAfterHours',
      'SiteEngineer', 'Notes', 'CreatedBy', 'CreatedAt', 'QrCode'
    ],
    dropdowns: { Status: ['Active', 'OnHold', 'Completed'] },
    statusColumns: ['Status']
  },
  ProjectAssignments: {
    headers: [
      'AssignmentID', 'ProjectID', 'UserID', 'RoleOnSite', 'AssignedFrom',
      'AssignedTo', 'Status',
      'ShiftID', 'WeeklyOff', 'DailyWage', 'AssignedBy', 'CreatedAt', 'Notes'
    ],
    dropdowns: {
      RoleOnSite: ['Supervisor', 'SiteIncharge', 'ProjectManager', 'Engineer',
        'Foreman', 'Mason', 'Carpenter', 'Electrician', 'Plumber',
        'Painter', 'Helper', 'Worker', 'Security', 'Other'],
      Status: ['Active', 'Ended']
    },
    statusColumns: ['Status']
  },
  Attendance: {
    headers: [
      'AttendanceID', 'UserID', 'ProjectID', 'Date', 'MarkedAt', 'Lat', 'Long',
      'DistanceFromSite', 'SelfieDriveLink', 'Status', 'DeviceID', 'ReviewedBy',
      'ReviewNote',
      'MarkedOutAt', 'OutLat', 'OutLong', 'HoursWorked', 'OvertimeHours',
      'LateMark', 'Source', 'CapturedAt', 'SyncedAt', 'FlagReason',
      'SelfieFileId', 'WeatherFlag', 'AccuracyMeters', 'CreatedAt'
    ],
    dropdowns: {
      Status: ATT_STATUS,
      Source: ATT_SOURCE,
      LateMark: ['Y', 'N'],
      WeatherFlag: ['', 'RainDay', 'ExtremeHeat', 'Closed']
    },
    statusColumns: ['Status']
  },
  LeaveRequests: {
    headers: [
      'LeaveID', 'UserID', 'FromDate', 'ToDate', 'Type', 'Reason', 'Status',
      'ApprovedBy', 'AppliedAt',
      'Days', 'AttachmentLink', 'ReviewedAt', 'ReviewNote', 'CancelledAt'
    ],
    dropdowns: {
      Type: LEAVE_TYPES,
      Status: ['Pending', 'Approved', 'Rejected', 'Cancelled']
    },
    statusColumns: ['Status']
  },
  ExpenseRequests: {
    headers: [
      'ExpenseID', 'UserID', 'ProjectID', 'Amount', 'Category', 'Description',
      'ProofDriveLink', 'Status', 'ApprovedBy', 'PayoutStatus', 'AppliedAt',
      'ReceiptNo', 'ProofFileId', 'ReviewedAt', 'ReviewNote', 'PaidOn'
    ],
    dropdowns: {
      Category: EXPENSE_CATEGORIES,
      Status: ['Pending', 'Approved', 'Rejected'],
      PayoutStatus: ['AddedToSalary', 'Pending', 'PaidCash']
    },
    statusColumns: ['Status']
  },
  SiteTransfers: {
    headers: [
      'TransferID', 'UserID', 'FromProjectID', 'ToProjectID', 'EffectiveDate',
      'TravelPaid', 'Status', 'ApprovedBy',
      'Reason', 'RoleOnSite', 'AppliedAt', 'ReviewedAt', 'ReviewNote'
    ],
    dropdowns: {
      TravelPaid: ['Y', 'N'],
      Status: ['Pending', 'Approved', 'Rejected', 'Cancelled']
    },
    statusColumns: ['Status']
  },
  Vendors: {
    headers: [
      'VendorID', 'VendorName', 'ContactPerson', 'Mobile', 'ProjectIDs', 'Status',
      'GST', 'Address', 'Email', 'RatePerHead', 'PaymentTerms', 'CreatedAt', 'Notes'
    ],
    dropdowns: { Status: ['Active', 'Inactive'] },
    statusColumns: ['Status']
  },
  VendorWorkers: {
    headers: [
      'EntryID', 'VendorID', 'ProjectID', 'WorkerName', 'PhotoDriveLink',
      'Designation', 'Date', 'Count', 'MarkedBy',
      'AadhaarMasked', 'Mobile', 'RatePerDay', 'AmountPayable', 'Status',
      'PhotoFileId', 'CreatedAt', 'Notes'
    ],
    dropdowns: { Status: ['Active', 'Left', 'Blocked'] },
    statusColumns: ['Status']
  },
  Holidays: {
    headers: [
      'HolidayID', 'Date', 'Name', 'ApplicableProjects',
      'Type', 'Year', 'Paid', 'CreatedAt', 'CreatedBy'
    ],
    dropdowns: { Type: ['Company', 'Project', 'Regional'], Paid: ['Y', 'N'] },
    statusColumns: []
  },
  Shifts: {
    headers: [
      'ShiftID', 'Name', 'StartTime', 'EndTime', 'ApplicableProjects',
      'BreakMinutes', 'OvertimeAfter', 'WindowStart', 'WindowEnd', 'Color',
      'CreatedAt', 'Notes'
    ],
    dropdowns: {},
    statusColumns: []
  },
  Documents: {
    headers: [
      'DocID', 'UserID', 'DocType', 'DriveLink', 'ExpiryDate', 'Status',
      'FileName', 'FileId', 'UploadedBy', 'UploadedAt', 'AlertSentAt',
      'ExpiryAlertDays', 'Notes'
    ],
    dropdowns: {
      DocType: DOC_TYPES,
      Status: ['Valid', 'ExpiringSoon', 'Expired', 'Rejected']
    },
    statusColumns: ['Status']
  },
  AuditLog: {
    headers: [
      'LogID', 'ActorUserID', 'Action', 'TargetEntity', 'Timestamp', 'Details',
      'ActorName', 'ActorRole', 'CompanyID', 'EntityID', 'UserAgent', 'Result'
    ],
    dropdowns: {},
    statusColumns: []
  },
  Notifications: {
    headers: [
      'NotifID', 'UserID', 'Message', 'Type', 'Read', 'CreatedAt',
      'Title', 'Channel', 'PayloadJSON', 'SentAt', 'Link', 'Priority'
    ],
    dropdowns: {
      Type: ['Info', 'Approval', 'Alert', 'Flagged', 'Expiry', 'Report', 'System'],
      Read: ['Y', 'N'],
      Priority: ['Low', 'Normal', 'High']
    },
    statusColumns: ['Read']
  },
  Settings: {
    headers: ['Key', 'Value', 'UpdatedAt', 'UpdatedBy', 'Description'],
    dropdowns: {},
    statusColumns: []
  },
  DeviceRegistry: {
    headers: [
      'DeviceID', 'UserID', 'DeviceFingerprint', 'RegisteredAt', 'LastUsedAt',
      'Status',
      'DeviceLabel', 'UserAgent', 'PendingFingerprint', 'RequestedAt',
      'ApprovedBy', 'ApprovedAt', 'LoginCount'
    ],
    dropdowns: { Status: ['Active', 'Blocked', 'PendingChange'] },
    statusColumns: ['Status']
  },
  RegularizationRequests: {
    headers: [
      'RequestID', 'UserID', 'ProjectID', 'Date', 'RequestedStatus', 'Reason',
      'ProofLink', 'ProofFileId', 'Status', 'ApprovedBy', 'AppliedAt',
      'ReviewedAt', 'ReviewNote', 'OriginalAttendanceID', 'InTime', 'OutTime'
    ],
    dropdowns: {
      RequestedStatus: ATT_STATUS,
      Status: ['Pending', 'Approved', 'Rejected']
    },
    statusColumns: ['Status']
  }
};

/** Ordered list of tabs created in every per-company spreadsheet. */
var COMPANY_TAB_ORDER = [
  'Settings', 'Users', 'Projects', 'ProjectAssignments', 'Attendance',
  'LeaveRequests', 'ExpenseRequests', 'SiteTransfers', 'RegularizationRequests',
  'Vendors', 'VendorWorkers', 'Holidays', 'Shifts', 'Documents',
  'Notifications', 'DeviceRegistry', 'AuditLog'
];

var PLATFORM_TAB_ORDER = ['CompanySignupRequests', 'CompanyRegistry', 'LoginIndex', 'PlatformAuditLog'];

/**
 * Authentication is declared once, per action, in the router's ACTIONS table
 * (04_Router.gs) — `auth: 'none' | 'user' | 'staff' | 'owner'`. There is
 * deliberately no second copy of that list here to drift out of sync; dev/verify.mjs
 * fails the build if anything else duplicates it.
 */
